### PR TITLE
Solve mutability issue when projecting point

### PR DESCRIPTION
**Pull request by lpereira95**
Avoid returning as projected point the input object (to avoid mutability issues, which are very often tricky to spot).

(I've quickly looked to all the projection functions and have only found this. Probably there's more behavior like this)

### CODE REVIEW

**Review by ninamiolane — COMMENTED** [review]
Thanks @lpereira95 ! I've tried to re-run the tests many times (in case the tests were failing just by "chance"), but each time it's tensorflow failing. Do you know what is going on?

**Comment by lpereira95** [comment]
I don't know what's going on, but I'll try to identify it.

**Comment by ninamiolane** [comment]
@lpereira95 any update on this?

**Comment by lpereira95** [comment]
This will be solved in a new PR.

**Pull request closed without merging**
