### PR TITLE
Created and tested polynomial_regression.py. 

### PR DESCRIPTION
**Pull request by mallelaan**
## Checklist

- [x] My pull request has a clear and explanatory title.
- [x] If neccessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [x] I have added apropriate unit tests.
- [x] I have made sure the code passes all unit tests. (refer to comment below)
- [x] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [x] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [x] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [x] I have linked to issues and PRs that are relevant to this PR.

## Description

(Partially) Implemented polynomial regression for LOGML project. I plan on completing it further over the next few days

## Issue

As part of LOGML

### CODE REVIEW

**Review by lpereira95 — CHANGES_REQUESTED** [review]
Thanks for the nice contribution @mallelaan!

I added some comments, but they're not very important in general. I think we need to rethink the code, because we repeat most of the methods from [geodesic regression](https://github.com/geomstats/geomstats/blob/master/geomstats/learning/geodesic_regression.py). What are the things that are different? `_model` only? Can't we go by inheritance?

**Comment by ninamiolane** [comment]
Hi, any update on this? @mallelaan Thanks!

**Comment by mallelaan** [comment]
Hi,
Sorry - I got super busy at work over the last few weeks but I'll give it
another crack as soon as I can. It is similar in concept to the geodesic
regression. However, that is because polynomial regression is similar in
concept to linear regression (in Euclidean space) no? I'm not sure what an
alternative would be.

-Arka

**Comment by mallelaan** [comment]
Just to add - the only other difference between this and Geodesic
Regression is that the shape of the parameter array varies depending on the
order of the polynomial. Some of the commented areas specifically address
that part. I'll see if I can optimize it further

**Comment by luisfpereira** [comment]
I'm closing this as it is continued in #1802.

**Pull request closed without merging**
