### PR TITLE
Change symmetric eigenvalue, eigenvector func from np to torch

### PR DESCRIPTION
**Pull request by cshewmake2**
Passed my local tests as well as all nose2 tests (excluding known karate club dataset import issue in a notebook).

### CODE REVIEW

**Comment by cshewmake2** [comment]
I just looked; I'm not sure that we have a unit test for this function.

**Comment by ninamiolane** [comment]
@clharris you might be interested in this!

@cshewmake2  thanks!! 🎉  We might have an issue later on if we want to perform eigenvalue decomposition of non-symmetric matrices. But since eigh is only used on symmetric matrices in our code base right now, it's all good!

**Comment by cshewmake2** [comment]
@ninamiolane, as I understand it, np.linalg.eigh is specifically built for Hermitian (conjugate symmetric) matrices. I agree, if we want to do eigenvalue decomposition for non-symmetric matrices, we'll have to use something else (e.g. we couldn't have used eigh either).

One possible issue is that torch.symeig supposedly only works on **real** symmetric matrices, whereas eigh can handle matrices with complex entries. So perhaps this will cause problems.

**Comment by ninamiolane** [comment]
Got it, thanks for the clarification!

**Pull request merged**
