### PR TITLE
No full import setup

### PR DESCRIPTION
**Pull request by ymontmarin**
## Checklist

- [x] My pull request has a clear and explanatory title.
- [x] If neccessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [x] I have added apropriate unit tests.
- [x] I have made sure the code passes all unit tests. (refer to comment below)
- [x] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [x] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [x] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [x] I have linked to issues and PRs that are relevant to this PR.

### CODE REVIEW

**Comment by ymontmarin** [comment]
Hi ! I needed this patch to be able to make a clean build for the conda recipe: https://github.com/conda-forge/staged-recipes/pull/18613

This trick is inspired from sklearn (https://github.com/scikit-learn/scikit-learn/blob/main/setup.py).

The idea is that __init__ on geomstats root folder is both the rightful location for the version and some import binding for the user. However, setup does not need the other import and should not have it. It is needed for isolated build (as in conda) or when there is some C++ or Cython.

Deepsource mention a bug risk however it is a well undertand behavior.

**Comment by ymontmarin** [comment]
Thank you for your help !

**Comment by lpereira95** [comment]
@ymontmarin, is this still required with the new `cfg`-based setup? Right now it should be possible to install `geomstats` without any dependency, as the package is not imported anymore during installation.

**Comment by ymontmarin** [comment]
`version = attr: geomstats.__version__` does not still do a python logic import ? Or it just stop at version, hence at the start of the file ?

If yes, I can try the recipe without the patch and let you know

**Comment by lpereira95** [comment]
If my knowledge is updated, setup.cfg should handle it without performing any import (probably through parsing).

Can you please try it out and let me know if it works?

**Comment by ymontmarin** [comment]
Will do this evening !

**Comment by ymontmarin** [comment]
It work with the cfg based setup !!!!

We can close this PR.

**Pull request closed without merging**
