### PR TITLE
Fix vectorization problem with zero values in exp map of Poincare ball

### PR DESCRIPTION
**Pull request by AliceLeBrigant**
Address [issue#854](https://github.com/geomstats/geomstats/issues/854).

### CODE REVIEW

**Comment by ninamiolane** [comment]
Thanks for fixing this! Good to merge when the following error is fixed in the unit tests 🎉 

```
======================================================================
ERROR: test_log_exp_ball_null_tangent (tests.test_hyperbolic_coords.TestHyperbolicCoords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geomstats/geomstats/tests/test_hyperbolic_coords.py", line 181, in test_log_exp_ball_null_tangent
    exp = self.ball_metric.exp(tangent_vec, x)
  File "/home/travis/build/geomstats/geomstats/geomstats/vectorization.py", line 104, in wrapper
    result = function(*vect_args, **vect_kwargs)
  File "/home/travis/build/geomstats/geomstats/geomstats/geometry/poincare_ball.py", line 271, in exp
    exp, base_points[zero_tan], zero_tan)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 2
```

**Review by ninamiolane — CHANGES_REQUESTED** [review]
Just need to fix the travis error.

**Comment by AliceLeBrigant** [comment]
Sorry I'm not familiar with Travis... ```test_hyperbolic_coords.py``` runs without errors on my machine. Do you know what I should check ? Thanks !

**Comment by ninamiolane** [comment]
@Hzaatiti @tgeral68 any idea on the travis error?

**Comment by AliceLeBrigant** [comment]
My bad, ```test_hyperbolic_coords.py``` was indeed not working. It should be fixed now !

**Comment by tgeral68** [comment]
Hi, I fixed this issue in another pull request. Looking closer at the code this check is not necessary anymore since it is partially checked before. The issue when considering zeros vector is division by zero caused when we use the norm of the tangent vector:
`direction = gs.einsum('...i,...->...i', tangent_vec, 1 / norm_tan)
`
However, looking closer at the code we replace null tangent_vector component by a value epsilon. 

```
if gs.any(zero_tan):
            norm_tan = gs.assignment(norm_tan, EPSILON, zero_tan)
```
We then compute the direction : 

` direction = gs.einsum('...i,...->...i', tangent_vec, 1 / norm_tan)
`
Thus, in case of zero vector direction will be zero vector too (norm is no more null but tangent_vec is). We then compute the exp by 
```
        exp = self.mobius_add(
            base_point,
            gs.einsum('...i,...->...i', direction, factor))

```
the mobius addition will return base_point if added to a zero vector. Thus exp(base_point, (0,....,0)) will return the correct results which is  base_point. To conclude, there is no need to check  zero tangent vectors anymore at this location in the code.

sorry for my late intervention.

**Comment by AliceLeBrigant** [comment]
Ok great ! Thanks for this better fix !

**Pull request closed without merging**
