### PR TITLE
Add notebook version of scripts in examples

### PR DESCRIPTION
**Pull request by chicken-biryani**
## Checklist

- [X] My pull request has a clear and explanatory title.
- [ ] If neccessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I have added apropriate unit tests.
- [ ] I have made sure the code passes all unit tests. (refer to comment below)
- [ ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ ] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [ ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [ ] I have linked to issues and PRs that are relevant to this PR.

## Description 

This pull request adds notebook versions of python scripts in examples.

Note: Currently I have just added the .ipynb for the scripts and not deleted the .py scripts.
I have made use of the p2j- https://pypi.org/project/p2j/  (install it and use the command "p2j <file name>")
The next stage of the notebooks is to convert them into proper how-tos.

## Issue
NA

## Additional context
NA

### CODE REVIEW

**Comment by lpereira95** [comment]
Thanks @chicken-biryani!

Does `p2j` convert one file at a time or the full folder?

I think the next step should be to create a small python script that transforms the `main` function in a normal code cell and its docstrings in a markdown cell that precedes it. Also, `if __name__ #...` should be removed (need to check if only `main` is called). I think [`nbconvert`](https://nbconvert.readthedocs.io/en/latest/) may need to be used here to properly modify the notebooks. Would you be willing to do this or do you want I quickly write the script?



(connected to #1524)

**Comment by chicken-biryani** [comment]
@lpereira95 I'd like to try it out.

**Comment by lpereira95** [comment]
Sure @chicken-biryani. But do not spend to much time on it. In the limit we do the conversion manually.

**Comment by ninamiolane** [comment]
@lpereira95 @chicken-biryani any update on this? 🙌

**Comment by chicken-biryani** [comment]
Hia,

I was supposed to proceed with this but couldn't figure out a script. Sorry.

**Comment by lpereira95** [comment]
@chicken-biryani, don't worry about the script. I'll have to look better to what is defined in these examples, in order to see if we gain anything in doing it automatically. Maybe it is enough to just do it manually, since we will have to do it only once.

For this task you may team up with @nanjekyejoannah. She'll be more concerned with the contributing guide next few weeks, but at some point we'll need to look to the examples.

**Pull request closed without merging**
