### PR TITLE
Add product positive reals and complex poincare disks

### PR DESCRIPTION
**Pull request by YannCabanes**
Add the `ProductPositiveRealsAndComplexPoincareDisks` manifold.

The `ProductPositiveRealsAndComplexPoincareDisks` manifold is defined as a
product manifold of the positive reals manifold and (n-1) complex Poincaré disks.
The positive reals and complex Poincaré disks product has a product metric.
The product metric on the positive reals and complex Poincaré disks product space is
the positive reals metric and (n - 1) complex Poincaré metrics multiplied by constants.
This product manifold can be used to represent Toeplitz HPD matrices.
The `ProductPositiveRealsAndComplexPoincareDisks` corresponds to
the one-dimensional case of `ProductHPDMatricesAndSiegelDisks`.
Indeed, `PositiveReals` is the one-dimensional case of `HPDMatrices` and
`ComplexPoincareDisk` is the one-dimensional case of `Siegel`.
In these one-dimensional manifolds, many simplifications occur compared with
the multidimensional manifolds since matrices commute in dimension 1.

References
----------
.. [Cabanes_2022] Yann Cabanes. Multidimensional complex stationary
    centered Gaussian autoregressive time series machine learning
    in Poincaré and Siegel disks: application for audio and radar
    clutter classification, PhD thesis, tel-03708515, 2022.
    https://theses.hal.science/tel-03708515
.. [Cabanes_CESAR_2019] Yann Cabanes, Frédéric Barbaresco, Marc Arnaudon et
    Jérémie Bigot. Unsupervised Machine Learning for Pathological Radar Clutter
    Clustering: the P-Mean-Shift Algorithm, IEEE, C&ESAR 2019, Rennes, France, 2019.
    https://hal.archives-ouvertes.fr/hal-02875430
.. [Cabanes_RADAR_2019] Yann Cabanes, Frédéric Barbaresco, Marc Arnaudon et
    Jérémie Bigot. Non-Supervised High Resolution Doppler Machine Learning for
    Pathological Radar Clutter, IEEE, RADAR 2019, Toulon, France, 2019.
    https://hal.archives-ouvertes.fr/hal-02875415
.. [Cabanes_GSI_2019] Yann Cabanes, Frédéric Barbaresco, Marc Arnaudon et
    Jérémie Bigot. Toeplitz Hermitian Positive Definite Matrix Machine Learning
    based on Fisher Metric, IEEE, GSI 2019, Toulouse, France, 2019.
    https://hal.archives-ouvertes.fr/hal-02875403
.. [Le_Brigant_2017] Alice Le Brigant. Probability on the spaces of curves and
    the associated metric spaces using information geometry; radar applications,
    PhD thesis, tel-01635258, 2017.
    https://theses.hal.science/tel-01635258
.. [Jeuris_2016] B. Jeuris and R. Vandebril. The Kahler mean of Block-Toeplitz
    matrices with Toeplitz structured blocks, 2016.
    https://epubs.siam.org/doi/pdf/10.1137/15M102112X
.. [Yang_2013] Marc Arnaudon, Frédéric Barbaresco and Le Yang. Riemannian Medians
    and Means With Applications to Radar Signal Processing, IEEE, 2013.

### CODE REVIEW

**Comment by YannCabanes** [comment]
There is a test error with the tensorflow backend.
The problem is the `PositiveReals` manifold is a manifold of reals and the `ComplexPoincareDisk` is a manifold of complex.
The `ProductPositiveRealsAndComplexPoincareDisks` uses `gs.stack` to stack a positive real with several complex values.
This returns an error for the tensorflow backend.

**Comment by YannCabanes** [comment]
```
=========================== short test summary info ============================
ERROR tests/tests_geomstats/test_product_positive_reals_and_poincare_disks.py - tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Pack as input #1(zero-based) was expected to be a double tensor but is a complex128 tensor [Op:Pack] name: stack
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by YannCabanes** [comment]
When we use the backends numpy, autograd or pytorch, the value of the positive real is automatically converted to the complex128 format when stacked with the complex values.
When we compute the `ProductPositiveRealsAndComplexPoincareDisks.squared_dist` the `PositiveReals.squared_dist` is called on a complex `point_a` and `point_b`. Then a complex distance is returned by `PositiveReals.squared_dist` (with zero imaginary part).
The `ProductPositiveRealsAndComplexPoincareDisks.squared_dist` is therefore complex since it is a linear combination of `PositiveReals.squared_dist` (complex) and `ComplexPoincareDisk.squared_dist` (real). 
This does not return a test error, but it is still an error.

**Comment by YannCabanes** [comment]
@lpereira95 
What I would like is:
- staking a real and complex values results in a complex vector,
- the output of `log`, `exp`, `inner_product` of `ProductPositiveRealsAndComplexPoincareDisks` to be complex,
- the output of `dist`, `squared_dist`, `norm`, `squared_norm` to be reals.

@lpereira95, how would you like to do that?
For the first point above, I suggest to modify the stack function in the tensorflow backend.
The second point should be automatically solved once the first point is soved.
For the third point, maybe we should modify the file `product_riemannian_metric.py`. What do you think?

**Comment by lpereira95** [comment]
@YannCabanes, I'm thinking about a solution where:

1. all the backends allow stack of real and complex, as you suggest (giving complex)
2. before sending a point to be manipulated in its corresponding factor, we convert it to real if the factor handles real numbers

I think everything else will work properly after these modifications.

For 2. I'll add the flag `is_complex` (or `is_real`) to the manifold, and modify product manifold accordingly.

I'll implement it in different PRs.

What do you think?

**Comment by YannCabanes** [comment]
@lpereira95
Yes, this solution sounds great!
Thank you for handling it!

**Comment by lpereira95** [comment]
@YannCabanes, I've changed the output of `inner_product` to be real in several complex manifolds. Now I've noticed you were asking it to be complex. Why?

If `inner_product` can be real, then we are done here (just wait to merge #1770).

**Comment by YannCabanes** [comment]
Hello @lpereira95,
Thank you for your work!
The `inner_product` on complex manifolds is not real in general.
It is Hermitian, which means that: `<a, b> = conj(<b, a>)`
As a consequence, `<a, a>` is always real. (Useful property to define a `norm` from the `inner_product`.)
For example, the standard complex vector space is named `hermitian` in geomstats:
https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/hermitian.py
Its `inner_product` is defined by:
`inner_product(tangent_vec_a, tangent_vec_b, base_point=None) = gs.dot(gs.conj(tangent_vec_a), tangent_vec_b)`
This `inner_product`  is not real in general.

**Comment by lpereira95** [comment]
Thanks @YannCabanes. I'll fix the changes I've done. I think in the near future we should add smoke data to some manifolds where this is reflected (i.e. at least an example of a inner product computation that is complex), so we ensure all the future changes will preserve that behavior.

After this, it will be ready to go.

**Comment by YannCabanes** [comment]
Hello @luisfpereira,
Could you fix the last problem (the `inner_product` of complex manifolds should be complex), resolve the conflicts and merge this PR please?
Tell me if there is anything that I should do.
Once this PR is merged, I will start a notebook using the `ProductPositiveRealsAndComplexPoincareDisks` manifold.

**Comment by luisfpereira** [comment]
@YannCabanes, after merging #1798, I think we are ready here.

Am I overlooking anything?

**Comment by YannCabanes** [comment]
Hello @luisfpereira,
Thanks a lot for your work.
Everything seems correct to me, you can merge.

**Review by luisfpereira — APPROVED** [review]

**Comment by luisfpereira** [comment]
Thanks @YannCabanes! Merging...

**Pull request merged**
