### PR TITLE
add missing notebook

### PR DESCRIPTION
**Pull request by SaitejaUtpala**

### CODE REVIEW

**Comment by SaitejaUtpala** [comment]
Professor @ninamiolane. This will add missing notebook.

**Review by ninamiolane — CHANGES_REQUESTED** [review]
Thanks! 🙌  Does that remove the Kendall visualization notebook though? Should we keep it?

**Comment by SaitejaUtpala** [comment]
sorry, removed it accidentally

**Review by ninamiolane — APPROVED** [review]
Great, thanks!

**Pull request merged**
