### PR TITLE
Add notebook version of python scripts in examples

### PR DESCRIPTION
**Pull request by chicken-biryani**
This pull request adds notebook versions of python scripts in examples.

Note: Currently I have just added the .ipynb for the scripts and not deleted the .py scripts

The next stage of the notebooks is to convert them into proper how-tos

## Checklist

- [X] My pull request has a clear and explanatory title.
- [ ] If neccessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I have added apropriate unit tests.
- [ ] I have made sure the code passes all unit tests. (refer to comment below)
- [ ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ ] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [ ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [ ] I have linked to issues and PRs that are relevant to this PR.

### CODE REVIEW

**Comment by chicken-biryani** [comment]
Ping @lpereira95

**Comment by chicken-biryani** [comment]
Will remove the previous commit so that it doesn't mess up.

**Comment by lpereira95** [comment]
@chicken-biryani can you please reopen a new draft PR with cleaner commits (meaning, only one commit after last master commit)?

Additionally, can you briefly explain the libraries you've used to convert the `.py` and respective commands?

P.S. Opening as draft is important because this is still idea prototyping... we really need to go deeper to understand if it is worth pursuing.

**Comment by lpereira95** [comment]
No problem @chicken-biryani. It is just because this PR will involve a lot of back and forth, so it is better to start clean.

**Pull request closed without merging**
