### PR TITLE
Switch autograd to jax backend

### LINKED ISSUE #800: Add JAX backend - autograd is deprecated
Autograd [1] is deprecated for JAX [2]. It would be great to add the JAX backend for deploying vector/matrix/tensor operations to GPUs/TPUs.

Quoting the autograd website:

> Note: Autograd is still being maintained but is no longer actively developed. The main developers (Dougal Maclaurin, David Duvenaud, Matt Johnson, and Jamie Townsend) are now working on JAX, with Dougal and Matt working on it full-time. JAX combines a new version of Autograd with extra features such as jit 

[1] https://github.com/HIPS/autograd
[2] https://jax.readthedocs.io/en/latest/notebooks/quickstart.html

### PR DESCRIPTION
**Pull request by johmathe**
Switch autograd to jax backend

fix #800

### CODE REVIEW

**Comment by nguigs** [comment]
I made some fixes to make it work with jax but it seems extremely slow compared to autograd. I ran the following test:
```python
from timeit import timeit

import geomstats.backend as gs
from geomstats.geometry.connection import Connection
from geomstats.geometry.hypersphere import Hypersphere


connection = Connection(2)
hypersphere = Hypersphere(2)
connection.christoffels = hypersphere.metric.christoffels

base_point = gs.array([[gs.pi / 3, gs.pi / 4], [gs.pi / 2, gs.pi / 4]])
point = gs.array([[1.0, gs.pi / 2], [gs.pi / 6, gs.pi / 3]])

max_shape = point.shape if point.ndim == 3 else base_point.shape
n_steps = 50
step = 'rk4'

def objective(velocity):
    """Define the objective function."""
    velocity = gs.array(velocity)
    velocity = gs.cast(velocity, dtype=base_point.dtype)
    velocity = gs.reshape(velocity, max_shape)
    delta = connection.exp(velocity, base_point, n_steps, step) - point
    return gs.sum(delta ** 2)

obj = gs.autograd.value_and_grad(objective)
timeit(lambda : obj(point - base_point), number=10)
```
This takes ~120s to run (with `gs=jax.numpy` and `gs.autograd=jax.autograd`), while it only takes 3s if this is run in the master branch (where `gs=autograd.numpy` and `gs.autograd=autograd`)

**Comment by ninamiolane** [comment]
Closing as we couldn't show that jax was improving performances, yet.

**Comment by nguigs** [comment]
@ninamiolane you had a summary of what didn't work out with geomstats, do you know where I could find it?

**Comment by ninamiolane** [comment]
@nguigs https://github.com/ninamiolane/geomstats/blob/demo-jax/notebooks/Summarizing%20Jax%20Issue.ipynb !

**Pull request closed without merging**
