### PR TITLE
Update sr metric and create notebook and tests

### PR DESCRIPTION
**Pull request by mortenapedersen**

### CODE REVIEW

**Comment by ninamiolane** [comment]
@lpereira95 @SaitejaUtpala any idea why the unit tests are not run on this PR? 🤔

**Comment by ninamiolane** [comment]
@mortenapedersen is this PR replacing PR #1464 and if so should we close PR #1464?

**Comment by SaitejaUtpala** [comment]
@ninamiolane  @lpereira95  Github actions is working fin, see #1469 (just checking sometimes it does't trigger)

**Comment by ninamiolane** [comment]
The tests are also not triggered on Morten's PR #1464. It seems weird that the GitHub actions would selectively choose Morten's PRs to avoid getting triggered. I remember this was happening in December too.

@mortenapedersen maybe try to accept the GitHub invite to the geomstats repository?

**Comment by mortenapedersen** [comment]
> The tests are also not triggered on Morten's PR #1464. It seems weird that the GitHub actions would selectively choose Morten's PRs to avoid getting triggered. I remember this was happening in December too.
> 
> @mortenapedersen maybe try to accept the GitHub invite to the geomstats repository?

I don't find any invite? I checked https://github.com/orgs/geomstats/invitation but there's nothing.

I closed #1464, that was a mistake!

**Comment by ninamiolane** [comment]
Thanks @mortenapedersen ! I have cancelled the old invite and resent on, see screenshot below.

Screen Shot 2022-04-11 at 7 19 12 AM

**Comment by mortenapedersen** [comment]
> Thanks @mortenapedersen ! I have cancelled the old invite and resent on, see screenshot below.
> 
> Screen Shot 2022-04-11 at 7 19 12 AM

Thanks, I just accepted. I redid the PR but still only deepsource is being run :/

**Comment by lpereira95** [comment]
I'm wondering if this may be somehow related with apps authorizations (e.g. @mortenapedersen in this [link](https://github.com/settings/apps/authorizations) does it tell you deepsource.io has access?).

Anyway, I've blackify and isorted your files @mortenapedersen (in fact, just to have a change to commit) and the actions were triggered. Looking forward to see what happens if you are the author of the commit!

**Comment by mortenapedersen** [comment]
> I'm wondering if this may be somehow related with apps authorizations (e.g. @mortenapedersen in this [link](https://github.com/settings/apps/authorizations) does it tell you deepsource.io has access?).
> 
> Anyway, I've blackified and isorted your files @mortenapedersen (in fact, just to have a change to commit) and the actions were triggered. Looking forward to see what happens if you are the author of the commit!
> 
> P.S. remember to pull my changes before a new commit.

Sorry Luis, I missed your comment about checking apps authorization on https://github.com/settings/apps/authorizations . 

Under 'Authorized github apps' only 'Review Notebook App' is listed. 

Under 'Installed GitHub Apps' and 'Authorized OAuth Apps' nothing is listed.

**Comment by ninamiolane** [comment]
@lpereira95 @mortenapedersen  any update on this? 🙌

**Comment by ninamiolane** [comment]
@lpereira95 @mortenapedersen any update on this? 🙌

**Comment by mortenapedersen** [comment]
Hi! I just pushed some small changes to this PR (I hope that's a correct phrasing). It seems that some things related to testing has changed since the PR was opened in April. The test-script test_sub_riemannian_metric.py didn't yield an error in April, but now yields the error "Undefined variable 'tests'" in the lines  @tests.conftest.autograd_tf_and_torch_only .

**Comment by mortenapedersen** [comment]
> > I'm wondering if this may be somehow related with apps authorizations (e.g. @mortenapedersen in this [link](https://github.com/settings/apps/authorizations) does it tell you deepsource.io has access?).
> > Anyway, I've blackified and isorted your files @mortenapedersen (in fact, just to have a change to commit) and the actions were triggered. Looking forward to see what happens if you are the author of the commit!
> > P.S. remember to pull my changes before a new commit.
> 
> @lpereira95 I missed your comment about checking apps authorization on https://github.com/settings/apps/authorizations .
> 
> Under 'Authorized github apps' only 'Review Notebook App' is listed.
> 
> Under 'Installed GitHub Apps' and 'Authorized OAuth Apps' nothing is listed.

Did my response to this help in some way?

**Comment by lpereira95** [comment]
@mortenapedersen, I'm merging this PR.

In the (near) future we will:

1. add `log` and `dist`
2. allow the use of different integrators and (probably) move symplectic euler step to `integrators`
3. verify if the code can be made faster by integrating in order to position or velocity (depending on the need) only


Notice the changes in the notebook. To run it with autograd you need to `export GEOMSTATS_BACKEND=autograd` before launching jupyter.

Thanks for the nice contribution!

**Pull request merged**
