### PR TITLE
Fix complex data type in squared_dist, norm and squared_norm in the manifold ProductPositiveRealsAndComplexPoincareDisks

### PR DESCRIPTION
**Pull request by YannCabanes**
The methods `squared_dist`, `norm` and `squared_norm` of the class `ProductPositiveRealsAndComplexPoincareDisksMetric` return complex data type.
This PR fixes this issue.

### CODE REVIEW

**Review by luisfpereira — CHANGES_REQUESTED** [review]
Thanks @YannCabanes.

I think the problem is not in `ProductPositiveRealsAndComplexPoincareDisksMetric`, but in `ProductManifold` or `ComplexPoincareDisk`. Can you please identify the root cause?

**Comment by YannCabanes** [comment]
Hello @luisfpereira,
I have checked the methods `dist`, `squared_dist`, `norm`, `squared_norm` of the class` ComplexPoincareDiskMetric`, they all return float values. The problem does not come from here.

The class `ProductPositiveRealsAndComplexPoincareDisksMetric` inherits from `ProductRiemannianMetric` which inherits from `RiemannianMetric` in which the `squared_norm` is defined as:
`self.inner_product(vector, vector, base_point)`
instead of:
`gs.real(self.inner_product(vector, vector, base_point))`.
Indeed, the `inner_product` of a complex manifold is complex but the `squared_norm` should be real.

In my opinion, it is cleaner to modify the method `squared_norm` of the class `RiemannianMetric` than to redefine the method `squared_norm` in the class `ProductPositiveRealsAndComplexPoincareDisksMetric`.

Do you allow be to replace 
`self.inner_product(vector, vector, base_point)` 
by `
gs.real(self.inner_product(vector, vector, base_point))`
in the method `squared_norm` of the class `RiemannianMetric`?

I would then remove the method `squared_norm` from the class `ProductPositiveRealsAndComplexPoincareDisksMetric`.

**Comment by luisfpereira** [comment]
Thanks for presenting different solutions @YannCabanes. I think we should go for 2., as it takes advantage of the work we've done in `ProductManifold` and keeps the solution for the problems in the place they arise.

**Comment by YannCabanes** [comment]
Hello @luisfpereira, I think that this PR is ready to be merged. Could you check please?

**Comment by YannCabanes** [comment]
All tests have passed except:
`Testing / build (ubuntu-latest, 3.11, pytorch, tests/tests_geomstats/) (pull_request) `
which is still in progress after a few hours.

**Comment by luisfpereira** [comment]
Thanks @YannCabanes. Probably related with triggering of tests due to lack of resources. In the it says it took a few minutes.

Looks good to me!

**Review by luisfpereira — APPROVED** [review]

**Comment by luisfpereira** [comment]
I'll just adapt some tests tolerances and merge after.

**Comment by YannCabanes** [comment]
Perfect, thanks a lot @luisfpereira

**Pull request merged**
