### PR TITLE
Add PullbackDiffeoMetric example to notebook 09

### PR DESCRIPTION
**Pull request by franciscoeacosta**
## Checklist

- [x] My pull request has a clear and explanatory title.
- [ ] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I added appropriate unit tests.
- [x] I made sure the code passes all unit tests. (refer to comment below)
- [ ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [x] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [x] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [ ] I linked to issues and PRs that are relevant to this PR.

### CODE REVIEW

**Comment by ninamiolane** [comment]
@luisfpereira would you know where the tests failures:
```ValueError: 'x0' must only have one dimension```
is coming from? 

It seems that you also have it on your PR #1767

**Comment by ninamiolane** [comment]
Very nice!!

**Comment by franciscoeacosta** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/geomstats/geomstats/pull/1868/discussion/#comment-1609233263'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by franciscoeacosta** [comment]
<p>Made the changes -- however, seems like </p><p> </p><p>"transported_tangent_vec" and "end_point" calculations are wrong. </p><p> </p><p>Not sure what the issue is?</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/geomstats/geomstats/pull/1868/discussion/#comment-1609233284'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ninamiolane** [comment]
There is one error coming from your line `import torch` which should be removed (see my comment on the notebook).

As for the computations of the parallel transport, this is probably a numerical "issue": the computation is faster and less precise, I assume that it would get back to its original value if the numerics parameters were set up differently.

The other errors are not coming from this PR, although I'm not sure why they come up.
- the keras error is probably an update on keras that changes the API.
- not sure about the others.

@luisfpereira do you agree for the numerics question? do you have insights about the other errors? Thanks!

**Comment by luisfpereira** [comment]
@ninamiolane, the `tensorflow` error is related with its last release. I've fixed it in #1873  by up-bounding the version.

For the parallel transport we can check if it is a numerical issue by performing computations with more precise numerical parameters. If it works out well, I guess we validate @ninamiolane's claim.  Then it should be OK to use less precise parameters to make it faster.

The errors not related with the notebooks are due to the recurrent issue of tolerances (I'm working on it in #1767 so that it stops to be a problem).

**Comment by franciscoeacosta** [comment]
@ninamiolane @luisfpereira 
it was indeed a numerics question, as surface.metric.exp_solver.integrator.n_steps was set to 1 and the computed vector remained unchanged by parallel transport. Setting n_steps = 20 gives much better values and is still fast

**Pull request merged**
