### PR TITLE
make logm,expm take multidimensional array

### PR DESCRIPTION
**Pull request by SaitejaUtpala**
following PR addresses problem of logm,expm taking only 2,3 dimensional array. 

following is the error when passing 4 dimensional array

```
import geomstats.geometry.spd_matrices as spd
i_3 = np.eye(3)
four_dim_mat = np.broadcast_to(i_3 , (2,2)+i_3.shape)  # shape is [2,2,3,3]
SPDmanifold = spd.SPDmatrices(four_dim_mat.shape[-1])
logm = SPDmanifold.logm(four_dim_mat)
```
Error :

`ValueError:axes don't match array`

with this PR, logm,expm now takes multidimensional (arbitrary dimension) array

### CODE REVIEW

**Review by ninamiolane — COMMENTED** [review]
Thanks for the PR! 🎉 

I forgot when we need to have logm, expm on multidimensional arrays: could you remind me of the usecase?

Also, we would need to add unit tests for this function, in the 4-D setting, to make sure they provide the results that we expect. Thanks!

**Comment by SaitejaUtpala** [comment]
> Thanks for the PR! 🎉
> 
> I forgot when we need to have logm, expm on multidimensional arrays: could you remind me of the usecase?
> 
> Also, we would need to add unit tests for this function, in the 4-D setting, to make sure they provide the results that we expect. Thanks!

@ninamiolane  
Its for shrinkage estimators. In shrinkage estimators we do joint mean estimation. Let's say we draw N samples (nxn matrices)  from P distributions, Data has shape  [p,N,n,n]. Sure will add tests

**Comment by SaitejaUtpala** [comment]
@ninamiolane @nguigs . Added Tests. Also DeepSource is asking to merge if statements in something I have not chagned. Even if I do, I don't think that will be readable.

**Comment by nguigs** [comment]
> @ninamiolane @nguigs . Added Tests. Also DeepSource is asking to merge if statements in something I have not chagned. Even if I do, I don't think that will be readable.

I think I did that merge in a previous PR, did you merge/rebase the master branch on your branch?

**Comment by SaitejaUtpala** [comment]
> > @ninamiolane @nguigs . Added Tests. Also DeepSource is asking to merge if statements in something I have not chagned. Even if I do, I don't think that will be readable.
> 
> I think I did that merge in a previous PR, did you merge/rebase the master branch on your branch? 

@nguigs  Hi. I merged the latest code. I think the checks are passing.

**Review by nguigs — APPROVED** [review]

**Pull request merged**
