### PR TITLE
refactor Preshape

### PR DESCRIPTION
**Pull request by SaitejaUtpala**

### CODE REVIEW

**Comment by nguigs** [comment]
Hi @SaitejaUtpala, great work on the refactoring! I think a parametrizer could be created for FiberBundles/QuotientMetrics with tests such as `to_horizontal_is_horizontal`, `to_vertical_is_vertical` etc. The metric on correlation matrices, and the one in #1362 use it.

**Comment by SaitejaUtpala** [comment]
@nguigs  Yup... we have already planned it in iteration 2.0

**Comment by nguigs** [comment]
Awesome! Let me know if you need help with that space!

**Comment by SaitejaUtpala** [comment]
> Awesome! Let me know if you need help with that structure!

sure definitely!

**Review by ninamiolane — APPROVED** [review]
Great, thanks!

**Pull request merged**
