### PR TITLE
Fix bug in both online kmeans examples

### PR DESCRIPTION
**Pull request by andreakiro**
A very short pull request to correct a minor bug in example files. This will make it easier for the next ones testing it :)

### CODE REVIEW

**Comment by ninamiolane** [comment]
@andreakiro this is not a bug, this how the line should be written with the latest version of geomstats, i.e. the master branch of the github repository. If you downloaded geomstats via pip, you might have a bug until we put the latest geomstats version on pypi.

@luisfpereira you confirm?

**Comment by luisfpereira** [comment]
Exactly, @ninamiolane.

**Comment by andreakiro** [comment]
Yes, indeed i've installed the package with pip!

**Comment by luisfpereira** [comment]
You're fully right @andreakiro: last version of `pip` still does not have this. By last version we are thinking `master` branch.

@ninamiolane, do you think the recent changes are worthy enough to justify a new release soon? From my side, I think we could probably release given all the changes in `learning`... (I would suggest as release date somwhere before next gsi)

**Pull request closed without merging**
