### PR TITLE
Fix inheritance of NFold and ProductManifold (Issue #1588)

### PR DESCRIPTION
**Pull request by Ryan-Vaughn**
Fixed NFoldManifold and NFoldMetric so that they both inherit from ProductManifold and ProductMetric respectively.
[https://github.com/geomstats/geomstats/issues/1588](url)

## Checklist

- [x] My pull request has a clear and explanatory title.
- [x] If neccessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I have added apropriate unit tests.
- [ ] I have made sure the code passes all unit tests. (refer to comment below)
- [x] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [x] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [x] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [x] I have linked to issues and PRs that are relevant to this PR.

### CODE REVIEW

**Comment by Ryan-Vaughn** [comment]
Hello! This is my first ever PR but I wanted to start getting involved in this project. Please let me know of anything that I can do to improve my contributions.

**Comment by ninamiolane** [comment]
Welcome, it is a pleasure to have you here! Thanks for the PR, we will be able to help from here. Also feel free to join our slack workspace (link on the readme) where we can further discuss.

@lpereira95 can help you with the tests, and @nanjekyejoannah you might be interested in the comments about the contributing guide.

**Comment by Ryan-Vaughn** [comment]
Thank you! It looks like my update has caused some circular dependencies, I
will try to resolve all the issues over the course of the week and get back
to you.

-Ryan

**Comment by ninamiolane** [comment]
@Ryan-Vaughn sounds good. Do let us know if we can help!

**Pull request closed without merging**
